<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GestionProductos.aspx.cs" Inherits="Tp_Integrador___Grupo3.GestionProductos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            width: 154px;
        }
        .auto-style4 {
            font-size: xx-large;
            font-weight: bold;
            text-decoration: underline;
        }
        .auto-style5 {
            width: 154px;
            height: 26px;
        }
        .auto-style6 {
            height: 26px;
        }
        .auto-style7 {
            width: 154px;
            height: 30px;
        }
        .auto-style8 {
            height: 30px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <br />
        <table style="width:100%">
            <tr>
                <td style="width:15%; text-align:center">
                    <asp:Button ID="Button1" runat="server" Text="Todas las categorias" OnClick="Button1_Click" />
                </td>
                <td style="width:65%">
                    <asp:TextBox ID="TextBox1" runat="server" Width="80%"></asp:TextBox>
                    <asp:Button ID="Button2" runat="server" Text="Buscar" OnClick="Button2_Click" Height="26px" />
                </td>
                <td>
                    <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/GestionMenu.aspx">Administrar página</asp:HyperLink>
                </td>
                <td>
                    <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/IniciarSesion.aspx">Cerrar Sesión</asp:HyperLink>
                </td>
            </tr>
        </table>
        <div>
            <h1 style="text-align: center; background-color: #00CC99; height: 35px; font-size: xx-large; color: #000000;" >GESTIÓN DE PRODUCTOS</h1>
            <br />
            Buscar Producto:
            <asp:TextBox ID="txtBuscar" runat="server" Width="153px"></asp:TextBox>
            <asp:Button ID="btnBuscar" runat="server" OnClick="btnBuscar_Click" Text="Buscar" />
            <br />
            <asp:GridView ID="grdProductos" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" CssClass="auto-style1" DataKeyNames="IdProducto_P" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" AutoGenerateDeleteButton="True" OnRowCancelingEdit="grdProductos_RowCancelingEdit" OnRowDeleting="grdProductos_RowDeleting" OnRowEditing="grdProductos_RowEditing" OnRowUpdating="grdProductos_RowUpdating">
                <Columns>
                    <asp:TemplateField HeaderText="Id Producto" InsertVisible="False" SortExpression="IdProducto_P">
                        <EditItemTemplate>
                            <asp:Label ID="lblId" runat="server" Text='<%# Bind("IdProducto_P") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblId" runat="server" Text='<%# Bind("IdProducto_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre" SortExpression="Nombre_P">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtNombre" runat="server" Text='<%# Bind("Nombre_P") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="txtNombre" ErrorMessage="RequiredFieldValidator">*Completar</asp:RequiredFieldValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNombre" runat="server" Text='<%# Bind("Nombre_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Detalle" SortExpression="Detalle_P">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtDetalle" runat="server" Text='<%# Bind("Detalle_P") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDetalle" runat="server" Text='<%# Bind("Detalle_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Categoria" SortExpression="Nombre_Cat">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlCategoriasEditar" runat="server" DataSourceID="SqlDataSource1" DataTextField="Nombre_Cat" DataValueField="IdCategoria_Cat">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT IdCategoria_Cat,Nombre_Cat FROM Categorias WHERE Estado_Cat = 1"></asp:SqlDataSource>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCategoria" runat="server" Text='<%# Bind("Nombre_Cat") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Marca" SortExpression="Nombre_M">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlMarcasEditar" runat="server" DataSourceID="SqlDataSourceMarcas" DataTextField="Nombre_M" DataValueField="IdMarca_M">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSourceMarcas" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Marcas] WHERE Estado_M = 1"></asp:SqlDataSource>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblMarca" runat="server" Text='<%# Bind("Nombre_M") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio" SortExpression="PrecioUnitario_P">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtPrecio" runat="server" Text='<%# Bind("PrecioUnitario_P") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="rfvPrecio" runat="server" ControlToValidate="txtPrecio" ErrorMessage="RequiredFieldValidator">*Completar</asp:RequiredFieldValidator>
                            <br />
                            <asp:RegularExpressionValidator ID="revPrecio" runat="server" ControlToValidate="txtPrecio" ErrorMessage="RegularExpressionValidator" ValidationExpression="^[1-9]\d*(,\d+)?$">*Solo ingrese Números</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("PrecioUnitario_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Stock" SortExpression="Stock_P">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtStock" runat="server" Text='<%# Bind("Stock_P") %>'></asp:TextBox>
                            <br />
                            <asp:RegularExpressionValidator ID="revStock" runat="server" ControlToValidate="txtStock" ErrorMessage="RegularExpressionValidator" ValidationExpression="^\d+$">*Solo ingrese Números</asp:RegularExpressionValidator>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblStock" runat="server" Text='<%# Bind("Stock_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Direccion de Imagen" SortExpression="Imagen_P">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtImagen" runat="server" Text='<%# Bind("Imagen_P") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblImagen" runat="server" Text='<%# Bind("Imagen_P") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
            <br />
            <asp:Label ID="lblMensaje" runat="server"></asp:Label>
            <br />
            <span class="auto-style4">Agregar Producto:</span><br />
            <br />
            <table class="auto-style2">
                <tr>
                    <td class="auto-style5">Nombre:</td>
                    <td class="auto-style6">
                        <asp:TextBox ID="txtNombre" runat="server" ValidationGroup="Agregar"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="txtNombre" ErrorMessage="RequiredFieldValidator" ValidationGroup="Agregar">*Completar</asp:RequiredFieldValidator>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">Detalle:</td>
                    <td>
                        <asp:TextBox ID="txtDetalle" runat="server" Height="89px" MaxLength="150" TextMode="MultiLine" Width="408px"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style7">Categoria:</td>
                    <td class="auto-style8">
                        <asp:DropDownList ID="ddlCategorias" runat="server">
                        </asp:DropDownList>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">Marca:</td>
                    <td>
                        <asp:DropDownList ID="ddlMarcas" runat="server">
                        </asp:DropDownList>
                    &nbsp;&nbsp;&nbsp;
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">Precio:</td>
                    <td>
                        <asp:TextBox ID="txtPrecio" runat="server" ValidationGroup="Agregar"></asp:TextBox>
                        <asp:RequiredFieldValidator ID="rfvNombre0" runat="server" ControlToValidate="txtPrecio" ErrorMessage="RequiredFieldValidator" ValidationGroup="Agregar">*Completar</asp:RequiredFieldValidator>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:RegularExpressionValidator ID="revPrecio" runat="server" ControlToValidate="txtPrecio" ErrorMessage="RegularExpressionValidator" ValidationExpression="^[1-9]\d*(\,\d+)?$" ValidationGroup="Agregar">*Solo Ingrese Numeros</asp:RegularExpressionValidator>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">Stock:</td>
                    <td>
                        <asp:TextBox ID="txtStock" runat="server" ValidationGroup="Agregar"></asp:TextBox>
                        <asp:RegularExpressionValidator ID="revStock" runat="server" ControlToValidate="txtStock" ErrorMessage="RegularExpressionValidator" ValidationExpression="^\d+$" ValidationGroup="Agregar">*Solo Ingrese Numeros</asp:RegularExpressionValidator>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">Direccion de la Imagen:</td>
                    <td>
                        <asp:TextBox ID="txtImagen" runat="server"></asp:TextBox>
                    </td>
                </tr>
            </table>
            <br />
            <asp:Button ID="btnAgregarProducto" runat="server" Text="Agregar Producto" Font-Bold="True" OnClick="btnAgregarProducto_Click" ValidationGroup="Agregar" />
            &nbsp;
            <asp:Label ID="lblNueva" runat="server"></asp:Label>
            <br />
        </div>
    </form>
</body>
</html>
