<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GestionMarca.aspx.cs" Inherits="Tp_Integrador___Grupo3.GestionMarca" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style3 {
            font-size: xx-large;
            color: #000000;
            height: 35px;
            text-align: center;
            background-color: #00CC99;
        }
        .auto-style4 {
            text-decoration: underline;
            font-size: xx-large;
        }
        .auto-style5 {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">

                <table style="width:100%">
                    <tr>
                        <td style="width:15%; text-align:center">
                            <asp:Button ID="Button2" runat="server" Text="Todas las categorias" OnClick="Button2_Click1" />
                        </td>
                        <td style="width:65%">
                            <asp:TextBox ID="TextBox2" runat="server" Width="80%"></asp:TextBox>
                            <asp:Button ID="Button3" runat="server" Text="Buscar" OnClick="Button3_Click" />
                        </td>
                        <td>
                            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/GestionMenu.aspx">Administrar pagina</asp:HyperLink>
                        </td>
                        <td>
                            <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/IniciarSesion.aspx">Cerrar Sesión</asp:HyperLink>
                        </td>
                    </tr>
                </table>
    
               
            <h1 class="auto-style3">GESTIÓN DE MARCAS</h1>
                <br />
            Buscar Marca:
            <asp:TextBox ID="txtBuscar" runat="server" Width="153px"></asp:TextBox>
            <asp:Button ID="btnBuscar" runat="server" OnClick="btnBuscar_Click" Text="Buscar" />
                <asp:GridView ID="grdGestionMarcas" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" Height="162px" Width="301px" AutoGenerateDeleteButton="True" OnRowDeleting="grdGestionMarcas_RowDeleting" OnRowEditing="grdGestionMarcas_RowEditing" OnRowUpdating="grdGestionMarcas_RowUpdating" OnRowCancelingEdit="grdGestionMarcas_RowCancelingEdit">
                    <Columns>
                        <asp:TemplateField HeaderText="Id Marca">
                            <ItemTemplate>
                                <asp:Label ID="lblIdMarca" runat="server" Text='<%# Bind("IdMarca_M") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Nombre">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtNombreMarca" runat="server" Text='<%# Bind("Nombre_M") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rfvNombre" runat="server" ControlToValidate="txtNombreMarca" ErrorMessage="RequiredFieldValidator">*Completar</asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblNombreMarca" runat="server" Text='<%# Bind("Nombre_M") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                    <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#007DBB" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#00547E" />
                </asp:GridView><br />
                <asp:Label ID="lblMensaje" runat="server"></asp:Label>
                <br />
                <span class="auto-style4"><strong>Agregar Marca:</strong></span><br />
                <br />
                Nombre Marca: <asp:TextBox ID="txtNombre" runat="server"></asp:TextBox>
                &nbsp;&nbsp;
                <asp:RequiredFieldValidator ID="rfvNombreMarca" runat="server" ControlToValidate="txtNombre" ErrorMessage="RequiredFieldValidator" ValidationGroup="Grupo1">*Completar</asp:RequiredFieldValidator>
                <br />
                <br />
                <asp:Label ID="lblNuevaMarca" runat="server"></asp:Label>
                <p>
                    <strong>
                    <asp:Button ID="btnMarca" runat="server" CssClass="auto-style5" Text="Guardar Marca" OnClick="btnMarca_Click" ValidationGroup="Grupo1" />
                    </strong>
                </p>
        </form>
</body>
</html>